delete_az_resources: False
workspace_name: testazml
resource_group_name: test
location: eastus 
experiment_name: runazml
script_name: run_workflow.py
job_file: ./jobs/experiment_job.yml
job_name: test_pipeline
job_script: job_workflow.py
storage_account_name: testsa
sa_resource_group_name: test
sa_container_name: rawdata
exclude_files: catalog