delete_az_resources: False
workspace_name: testazml
resource_group_name: test
location: eastus 
experiment_name: runazml
script_name: run_workflow.py
instance_file: ./jobs/create-instance.yml
job_file: ./jobs/pipeline_job.yml
job_script: job_workflow.py
storage_account_name: testsa
sa_resource_group_name: test
sa_container_name: rawdata
sa_container_directory: /
exclude_files: catalog
sql_server_name: gentestsrv01 
database_name: testdbsrv01