name: "Gemfury private release python package"

on:
    push:
      branches:
        - 'main'
      paths:
        - 'PyOrchDB/VERSION'

jobs:
  build-and-publish-to-gemfury:
    name: Build distribution
    runs-on: ubuntu-latest
    env:
        GEMFURY_PUSH_URL: ${{ secrets.GEMFURY_PUSH_URL }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Publish to Gemfury
      shell: bash
      run: |
        chmod +x publish_package_to_gemfury.sh
        ./publish_package_to_gemfury.sh .

    - name: Get package version
      id: get_version
      run: |
        version=$(python setup.py --version)
        echo "::set-output name=version::$version"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
    
